# Generated by Django 6.0 on 2026-05-30 16:57

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(verbose_name='Текст документа')),
            ],
            options={
                'verbose_name': 'Юридическая страница',
                'verbose_name_plural': 'Юридические страницы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='Город')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Рейтинг')),
                ('tour_label', models.CharField(blank=True, max_length=40, verbose_name='Метка тура')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('avatar_color', models.CharField(default='#28B5FF', max_length=7, verbose_name='Цвет аватара')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='WhyUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('i-bus', 'Транспорт'), ('i-mountain', 'Горы / проживание'), ('i-coffee', 'Питание / кофе'), ('i-guide', 'Гид'), ('i-swim', 'SUP / вода'), ('i-boat', 'Катер'), ('i-star', 'Экскурсии'), ('i-hat', 'Головной убор'), ('i-glasses', 'Очки'), ('i-sun', 'Крем SPF'), ('i-shoe', 'Обувь'), ('i-umbrella', 'Дождевик'), ('i-cash', 'Деньги'), ('i-jacket', 'Тёплая одежда'), ('i-battery', 'Зарядка'), ('i-smile', 'Настроение')], default='i-star', max_length=30)),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Почему мы',
                'verbose_name_plural': 'Почему мы',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_headline', models.CharField(default='Vibe Turistic', max_length=120, verbose_name='Заголовок героя')),
                ('hero_ribbon', models.CharField(default='№1 молодёжные туры по Дагестану', max_length=120, verbose_name='Лента (бейдж)')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('hero_bg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('vk', models.URLField(blank=True, verbose_name='VK')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('subscribers', models.CharField(default='31,8K', max_length=20, verbose_name='Подписчики')),
                ('rating', models.CharField(default='5,0', max_length=10, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=27, verbose_name='Кол-во отзывов')),
                ('cookie_text', wagtail.fields.RichTextField(blank=True, verbose_name='Текст cookie-баннера')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TourPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Индивидуальный (цена скрыта)')),
                ('badge', models.CharField(blank=True, max_length=40, verbose_name='Бейдж')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Короткое описание')),
                ('duration_days', models.PositiveIntegerField(default=5, verbose_name='Дней')),
                ('duration_label', models.CharField(default='5 дней / 4 ночи', max_length=40, verbose_name='Длительность')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Цена, ₽')),
                ('prepay', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Предоплата, ₽')),
                ('group_size', models.CharField(default='до 18', max_length=40, verbose_name='Размер группы')),
                ('meet_time', models.CharField(default='8:30', max_length=40, verbose_name='Сбор тура')),
                ('return_time', models.CharField(default='после 20:00', max_length=40, verbose_name='Вылет обратно')),
                ('important_note', wagtail.fields.RichTextField(blank=True, verbose_name='Что важно знать (дисклеймер)')),
                ('card_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('excluded_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('included_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(choices=[('i-bus', 'Транспорт'), ('i-mountain', 'Горы / проживание'), ('i-coffee', 'Питание / кофе'), ('i-guide', 'Гид'), ('i-swim', 'SUP / вода'), ('i-boat', 'Катер'), ('i-star', 'Экскурсии'), ('i-hat', 'Головной убор'), ('i-glasses', 'Очки'), ('i-sun', 'Крем SPF'), ('i-shoe', 'Обувь'), ('i-umbrella', 'Дождевик'), ('i-cash', 'Деньги'), ('i-jacket', 'Тёплая одежда'), ('i-battery', 'Зарядка'), ('i-smile', 'Настроение')], default='i-star', max_length=30)),
                ('title', models.CharField(max_length=80)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='tours.tourpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(choices=[('i-bus', 'Транспорт'), ('i-mountain', 'Горы / проживание'), ('i-coffee', 'Питание / кофе'), ('i-guide', 'Гид'), ('i-swim', 'SUP / вода'), ('i-boat', 'Катер'), ('i-star', 'Экскурсии'), ('i-hat', 'Головной убор'), ('i-glasses', 'Очки'), ('i-sun', 'Крем SPF'), ('i-shoe', 'Обувь'), ('i-umbrella', 'Дождевик'), ('i-cash', 'Деньги'), ('i-jacket', 'Тёплая одежда'), ('i-battery', 'Зарядка'), ('i-smile', 'Настроение')], default='i-star', max_length=30)),
                ('text', models.CharField(max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='tours.tourpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_items', to='tours.tourpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Начало')),
                ('date_to', models.DateField(verbose_name='Конец')),
                ('seats_left', models.PositiveIntegerField(default=18, verbose_name='Осталось мест')),
                ('status', models.CharField(choices=[('ok', 'есть места'), ('low', 'мало мест'), ('full', 'нет мест')], default='ok', max_length=4, verbose_name='Статус')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourpage', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Заезд',
                'verbose_name_plural': 'Заезды',
                'ordering': ['date_from'],
            },
        ),
    ]
