# Generated by Django 6.0 on 2026-05-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyusitem',
            name='theme',
            field=models.CharField(choices=[('prog', 'Синий'), ('sched', 'Жёлтый'), ('rev', 'Розовый'), ('why', 'Зелёный'), ('ask', 'Фиолетовый')], default='prog', max_length=10, verbose_name='Цвет иконки'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='meet_time',
            field=models.CharField(blank=True, default='8:30', max_length=40, verbose_name='Сбор тура'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='return_time',
            field=models.CharField(blank=True, default='после 20:00', max_length=40, verbose_name='Вылет обратно'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Короткое описание'),
        ),
    ]
