# Generated by Django 6.0 on 2026-05-31 12:19

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourgalleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Описание тура'),
        ),
        migrations.AlterField(
            model_name='excludeditem',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='includeditem',
            name='icon',
            field=models.CharField(choices=[('i-bus', 'Транспорт'), ('i-mountain', 'Горы / проживание'), ('i-coffee', 'Питание / кофе'), ('i-guide', 'Гид'), ('i-swim', 'SUP / вода'), ('i-boat', 'Катер'), ('i-star', 'Экскурсии'), ('i-hat', 'Головной убор'), ('i-glasses', 'Очки'), ('i-sun', 'Крем SPF'), ('i-shoe', 'Обувь'), ('i-umbrella', 'Дождевик'), ('i-cash', 'Деньги'), ('i-jacket', 'Тёплая одежда'), ('i-battery', 'Зарядка'), ('i-smile', 'Настроение')], default='i-star', max_length=30, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='includeditem',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='packingitem',
            name='icon',
            field=models.CharField(choices=[('i-bus', 'Транспорт'), ('i-mountain', 'Горы / проживание'), ('i-coffee', 'Питание / кофе'), ('i-guide', 'Гид'), ('i-swim', 'SUP / вода'), ('i-boat', 'Катер'), ('i-star', 'Экскурсии'), ('i-hat', 'Головной убор'), ('i-glasses', 'Очки'), ('i-sun', 'Крем SPF'), ('i-shoe', 'Обувь'), ('i-umbrella', 'Дождевик'), ('i-cash', 'Деньги'), ('i-jacket', 'Тёплая одежда'), ('i-battery', 'Зарядка'), ('i-smile', 'Настроение')], default='i-star', max_length=30, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='packingitem',
            name='note',
            field=models.CharField(blank=True, max_length=120, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='packingitem',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок дня')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание (под заголовком)')),
                ('description', wagtail.fields.RichTextField(verbose_name='Описание дня')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='tours.tourpage')),
            ],
            options={
                'verbose_name': 'День маршрута',
                'verbose_name_plural': 'Дни маршрута',
            },
        ),
    ]
