# Generated by Django 6.0 on 2026-05-31 12:27

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourpage_description_alter_excludeditem_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='tour',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_set', to='tours.tourpage', verbose_name='Тур'),
        ),
    ]
