# Generated by Django 6.0 on 2026-06-02 14:05

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_departure_tour'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фон героя'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото карточки'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='excluded_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото блока «Что не входит»'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Главное фото (баннер)'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='included_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото блока «Что входит»'),
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', wagtail.fields.RichTextField(verbose_name='Ответ')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='tours.homepage')),
            ],
            options={
                'verbose_name': 'Вопрос / Ответ',
                'verbose_name_plural': 'Вопросы / Ответы',
            },
        ),
    ]
