# Generated by Django 6.0 on 2026-06-02 14:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_faq_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeExcludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_excluded_items', to='tours.homepage')),
            ],
            options={
                'verbose_name': 'Доп. расходы',
                'verbose_name_plural': 'Доп. расходы',
            },
        ),
        migrations.CreateModel(
            name='HomeIncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(choices=[('i-bus', 'Транспорт'), ('i-mountain', 'Горы / проживание'), ('i-coffee', 'Питание / кофе'), ('i-guide', 'Гид'), ('i-swim', 'SUP / вода'), ('i-boat', 'Катер'), ('i-star', 'Экскурсии'), ('i-hat', 'Головной убор'), ('i-glasses', 'Очки'), ('i-sun', 'Крем SPF'), ('i-shoe', 'Обувь'), ('i-umbrella', 'Дождевик'), ('i-cash', 'Деньги'), ('i-jacket', 'Тёплая одежда'), ('i-battery', 'Зарядка'), ('i-smile', 'Настроение')], default='i-star', max_length=30, verbose_name='Иконка')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_included_items', to='tours.homepage')),
            ],
            options={
                'verbose_name': 'Включено в стоимость',
                'verbose_name_plural': 'Включено в стоимость',
            },
        ),
    ]
